import type { Locale } from "./legal";

export const ui = {
  es: {
    lang: "Español",
    title: "Consentimiento informado",
    subtitle: "Rellena solo tus datos. El texto legal se acepta después de firmar.",
    fullName: "Nombre y apellidos",
    dni: "DNI / NIE",
    birthDate: "Fecha de nacimiento",
    address: "Dirección",
    phone: "Teléfono",
    email: "Email",
    bodyZone: "Zona anatómica del tatuaje",
    inkBrand: "Marca de tinta / pigmento",
    inkLot: "Lote",
    inkExpiry: "Caducidad",
    minor: "Soy menor o no capaz (firma el representante)",
    repName: "Representante legal (nombre)",
    repDni: "Representante legal (DNI)",
    sign: "Firma de la persona usuaria",
    signRep: "Firma del representante",
    placeholder: "Firme aquí",
    clear: "Borrar firma",
    legal: "Texto legal (Decreto 71/2017)",
    accept: "He leído el texto legal y presto mi consentimiento",
    signFirst: "Firma primero para poder aceptar el texto legal.",
    submit: "Confirmar consentimiento",
    sending: "Guardando…",
    thanks: "Consentimiento guardado. Gracias.",
    error: "Revisa los campos y la firma.",
  },
  en: {
    lang: "English",
    title: "Informed consent",
    subtitle: "Fill in your details only. Legal text is accepted after you sign.",
    fullName: "Full name",
    dni: "ID / passport",
    birthDate: "Date of birth",
    address: "Address",
    phone: "Phone",
    email: "Email",
    bodyZone: "Body area to tattoo",
    inkBrand: "Ink / pigment brand",
    inkLot: "Lot",
    inkExpiry: "Expiry",
    minor: "I am a minor or lack capacity (legal representative signs)",
    repName: "Legal representative (name)",
    repDni: "Legal representative (ID)",
    sign: "Client signature",
    signRep: "Representative signature",
    placeholder: "Sign here",
    clear: "Clear signature",
    legal: "Legal text (Andalusia Decree 71/2017)",
    accept: "I have read the legal text and give my consent",
    signFirst: "Sign first to accept the legal text.",
    submit: "Confirm consent",
    sending: "Saving…",
    thanks: "Consent saved. Thank you.",
    error: "Check the fields and your signature.",
  },
} as const;

export function t(locale: Locale) {
  return ui[locale];
}
